package com;

import com.intellij.openapi.options.Configurable;
import com.intellij.openapi.options.ConfigurationException;
import com.intellij.openapi.options.SearchableConfigurable;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.util.ui.ColorIcon;
import org.jetbrains.annotations.Nls;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionListener;

/**
 * @author zn
 */
public class InputJira implements SearchableConfigurable, Configurable.NoScroll {
	private JPanel panel1;
	private JTextField host;
	private JTextField user;
	private JPasswordField password;
	private JButton login;
	private JComboBox titleFont;
	private JComboBox contentFont;
	private JColorChooser colorSelect;
	private JRadioButton titleBtn;
	private JRadioButton contentBtn;
	private JLabel contentColorShow;
	private JLabel titleColorShow;
	private ButtonGroup colorBtnGroup;

	private Color contentColor;
	private Color titleColor;

	public JPanel getPanel1() {
		return panel1;
	}

	public JTextField getHost() {
		return host;
	}

	public JTextField getUser() {
		return user;
	}

	public JPasswordField getPassword() {
		return password;
	}

	public JButton getLogin() {
		return login;
	}

//		public static void main(String[] args) {
//		JFrame frame = new JFrame("InputJira");
//		frame.setContentPane(new InputJira().panel1);
//		frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
//		frame.pack();
//		frame.setVisible(true);
//	}

	{
		$$$setupUI$$$();
	}

	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$() {
		panel1 = new JPanel();
		panel1.setLayout(new GridLayoutManager(5, 2, new Insets(0, 0, 0, 0), -1, -1));
		final JPanel panel2 = new JPanel();
		panel2.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
		panel1.add(panel2, new GridConstraints(0, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
		final JLabel label1 = new JLabel();
		label1.setText("host:         ");
		panel2.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		host = new JTextField();
		panel2.add(host, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
		final JPanel panel3 = new JPanel();
		panel3.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
		panel1.add(panel3, new GridConstraints(1, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
		final JLabel label2 = new JLabel();
		label2.setText("user:         ");
		panel3.add(label2, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		user = new JTextField();
		panel3.add(user, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
		final JPanel panel4 = new JPanel();
		panel4.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
		panel1.add(panel4, new GridConstraints(2, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
		final JLabel label3 = new JLabel();
		label3.setText("password: ");
		panel4.add(label3, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		password = new JPasswordField();
		panel4.add(password, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
		final JPanel panel5 = new JPanel();
		panel5.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
		panel1.add(panel5, new GridConstraints(3, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
		final JPanel panel6 = new JPanel();
		panel6.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
		panel1.add(panel6, new GridConstraints(4, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
		login = new JButton();
		login.setText("login");
		panel6.add(login, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
	}

	/**
	 * @noinspection ALL
	 */
	public JComponent $$$getRootComponent$$$() {
		return panel1;
	}


	@NotNull
	@Override
	public String getId() {
		return "jiraSetting";
	}

	@Nls(capitalization = Nls.Capitalization.Title)
	@Override
	public String getDisplayName() {
		return "jira setting";
	}

	@Nullable
	@Override
	public JComponent createComponent() {
		initFontSizeSelect();
		initSettingState();
		initListener();
		return panel1;
	}

	public void initFontSizeSelect() {
		for (int i = 10; i < 31; i++) {
			titleFont.addItem(i);
			contentFont.addItem(i);
		}
	}
	private void initListener() {
		ActionListener loginListener = e -> {
			loadSetting();
			ShowIssue.reLogin(JiraSetting.getInstance().getState());
		};
		login.addActionListener(loginListener);
	}

	private void initSettingState() {
		JiraSettingState jiraSettingState = JiraSetting.getInstance().getState();
		host.setText(jiraSettingState.getHost());
		user.setText(jiraSettingState.getUser());
		password.setText(jiraSettingState.getPassword());
		titleFont.setSelectedItem(jiraSettingState.getTitleSize());
		contentFont.setSelectedItem(jiraSettingState.getContentSize());

		titleColor = Color.decode(jiraSettingState.getTitleColor() == null ? "-1" : jiraSettingState.getTitleColor());
		contentColor = Color.decode(jiraSettingState.getContentColor() == null ? "-1" : jiraSettingState.getContentColor());

		titleBtn.setSelected(true);
		colorSelect.setColor(titleColor);
		titleColorShow.setIcon(new ColorIcon(30, titleColor));
		contentColorShow.setIcon(new ColorIcon(30, contentColor));
	}

	@Override
	public boolean isModified() {
		//compare state and label return true or false
		setColor();
		return true;
	}

	private void setColor() {
		Color temp = colorSelect.getColor();
		if (titleBtn.isSelected()) {
			titleColor = temp;
			titleColorShow.setIcon(new ColorIcon(30, temp));
		}else {
			contentColor = temp;
			contentColorShow.setIcon(new ColorIcon(30, temp));
		}
	}

	@Override
	public void apply() throws ConfigurationException {
		//save conf
		loadSetting();
	}

	private void loadSetting() {
		String titColorStr = titleColor.getRGB() + "";
		String contColorStr = contentColor.getRGB() + "";
		String hostText = host.getText();
		String userText = user.getText();
		String passwordText = String.valueOf(password.getPassword());
		int titleSize = Integer.parseInt(titleFont.getSelectedItem().toString());
		int contentSize = Integer.parseInt(contentFont.getSelectedItem().toString());
		JiraSetting.getInstance().loadState(new JiraSettingState(hostText, userText, passwordText,titleSize, contentSize, titColorStr, contColorStr));
	}
}
